EXPERIMENT_RUN: 001

MODEL:
  PROTOTYPE_SHAPE: (2000, 128, 1, 1)
  ADD_ON_LAYERS_TYPE: regular


DATASET:
  NAME: bioscan
  NUM_CLASSES: 40
  IMAGE: 
    SIZE: 256
    TRAIN_DIR: "datasets/bioscan/train_diptera_augmented"
    TEST_DIR: "datasets/bioscan/test_diptera"
    TRAIN_PUSH_DIR: "datasets/bioscan/train_diptera"
    TRAIN_BATCH_SIZE: 80
    TRANSFORM_MEAN: (0.485, 0.456, 0.406) 
    TRANSFORM_STD: (0.229, 0.224, 0.225)

OUTPUT:
  MODEL_DIR: "./saved_models/bioscan"
  IMG_DIR: "./saved_models/bioscan/img"
  WEIGHT_MATRIX_FILENAME: 'outputL_weights'
  PROTOTYPE_IMG_FILENAME_PREFIX: 'prototype-img'
  PROTOTYPE_SELF_ACT_FILENAME_PREFIX: 'prototype-self-act'
  PROTO_BOUND_BOXES_FILENAME_PREFIX: 'bb'
