EXPERIMENT_RUN: 001

MODEL:
    PROTOTYPE_SHAPE: [2000, 128, 1, 1]

DATASET:
    NAME: cub
    NUM_CLASSES: 200
    TRAIN_BATCH_SIZE: 80
    TEST_BATCH_SIZE: 80

    IMAGE:
        SIZE: 224
        TRAIN_DIR: "datasets/cub200_cropped/train_cropped_augmented"
        TEST_DIR: "datasets/cub200_cropped/test_cropped"
        TRAIN_PUSH_DIR: "datasets/cub200_cropped/train_cropped"
        TRANSFORM_MEAN: [0.485, 0.456, 0.406]
        TRANSFORM_STD: [0.229, 0.224, 0.225]

OUTPUT:
    MODEL_DIR: "saved_models/cub/vgg19/003"
    IMG_DIR: "saved_models/cub/vgg19/003/img"
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
