EXPERIMENT_RUN: 001

MODEL:
    PROTOTYPE_DISTANCE_FUNCTION: "cosine"
    PROTOTYPE_ACTIVATION_FUNCTION: "linear"
    BACKBONE: "pretrained_backbones/40w-64-deep_6.pth"

DATASET:
    NAME: "genetics"
    NUM_CLASSES: 40
    TRAIN_BATCH_SIZE: 80
    TEST_BATCH_SIZE: 100

    GENETIC:
        SIZE: 720
        TAXONOMY_NAME: "family"
        ORDER_NAME: "Diptera"
        TRANSFORM: "onehot"
        PROTOTYPE_SHAPE: (1600, 64, 1, 1) # 40 * DATASET_NUM_CLASSES
        FIX_PROTOTYPES: True
        TRAIN_PATH: "datasets/genetics/small_diptera_family-train.tsv"
        TRAIN_PUSH_DIR: "datasets/genetics/small_diptera_family-train.tsv"
        VALIDATION_PATH: "datasets/genetics/small_diptera_family-validation.tsv"

OUTPUT:
    NO_SAVE: True
    MODEL_DIR: "saved_models/genetics"
    IMG_DIR: "saved_models/genetics"
OPTIM:
    PUSH_START: 5
    PUSH_EPOCHS: [5, 10, 15, 20, 30, 40, 50, 60, 70, 80]
