EXPERIMENT_RUN: 001

MODEL:
  PROTOTYPE_DISTANCE_FUNCTION: 'cosine'
  PROTOTYPE_ACTIVATION_FUNCTION: 'linear'


DATASET:
  NAME: 'genetics'
  NUM_CLASSES: 40
  TRAIN_BATCH_SIZE: 80
  TEST_BATCH_SIZE: 100

  GENETIC:
  
    SIZE: 720
    PROTOTYPE_SHAPE: (400, 128, 1, 8)
    TAXONOMY_NAME: 'family'
    ORDER_NAME: 'Diptera'
    TRANSFORM: 'onehot'

    TRAIN_DIR: "./data/BIOSCAN-1M/small_diptera_family-train.tsv"
    TRAIN_PUSH_DIR: "./data/BIOSCAN-1M/small_diptera_family-validation.tsv"
    TEST_DIR: "./data/BIOSCAN-1M/small_diptera_family-test.tsv"


OUTPUT:
  NO_SAVE: True