EXPERIMENT_RUN: 001

MODEL:
  PROTOTYPE_DISTANCE_FUNCTION: 'cosine'
  PROTOTYPE_ACTIVATION_FUNCTION: 'linear'

DATASET:
  NAME: multimodal
  NUM_CLASSES: 40
  TRAIN_BATCH_SIZE: 80
  TRAIN_PUSH_BATCH_SIZE: 75
  TEST_BATCH_SIZE: 100

  IMAGE: 
    SIZE: 256
    PROTOTYPE_SHAPE: (2000, 128, 1, 1)
    MODEL_PATH: "datasets/bioscan" # should be updated 
    TRAIN_DIR: "datasets/bioscan/train_diptera_augmented"
    TEST_DIR: "datasets/bioscan/test_diptera"
    TRAIN_PUSH_DIR: "datasets/bioscan/train_diptera"
    TRANSFORM_MEAN: (0.485, 0.456, 0.406)
    TRANSFORM_STD: (0.229, 0.224, 0.225)

  GENETIC:
    SIZE: 720
    PROTOTYPE_SHAPE: (1600, 128, 1, 8)
    TAXONOMY_NAME: 'family'
    ORDER_NAME: 'Diptera'
    TRANSFORM: 'onehot'

    MODEL_PATH: "./data"
    TRAIN_PATH: "datasets/genetics/multimodal/train_diptera_augmented.tsv"
    TRAIN_PUSH_DIR: "datasets/genetics/train_diptera.tsv"
    VALIDATION_PATH: "datasets/genetics/multimodal/test_diptera.tsv"

OUTPUT:
  MODEL_DIR: "./saved_models"
  IMG_DIR: "./saved_models/img"
  WEIGHT_MATRIX_FILENAME: 'outputL_weights'
  PROTOTYPE_IMG_FILENAME_PREFIX: 'prototype-img'
  PROTOTYPE_SELF_ACT_FILENAME_PREFIX: 'prototype-self-act'
  PROTO_BOUND_BOXES_FILENAME_PREFIX: 'bb'
